apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-spark-fx
  namespace: streaming
spec:
  schedule: "55 16 * * 0"
  timeZone: "America/New_York"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          restartPolicy: Never
          serviceAccountName: streaming-sa
          containers:
            - name: start-fx
              image: bitnami/kubectl:1.30.0
              command:
                - /bin/sh
                - -c
                - kubectl -n streaming scale deployment spark-fx --replicas=1
