apiVersion: batch/v1
kind: CronJob
metadata:
  name: start-equity-producer
  namespace: streaming
spec:
  schedule: "31 9 * * 1-5"
  timeZone: "America/New_York"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          restartPolicy: Never
          serviceAccountName: streaming-sa
          containers:
            - name: start-equity-producer
              image: bitnami/kubectl:1.30.0
              command:
                - /bin/sh
                - -c
                - kubectl -n streaming scale deployment equity-producer --replicas=1
