apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: streaming

spec:
  serviceName: zookeeper

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  replicas: {{ .Values.replicas.zookeeper }}

  selector:
    matchLabels:
      app: zookeeper

  template:
    metadata:
      labels:
        app: zookeeper
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

    spec:
      terminationGracePeriodSeconds: 60

      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}

      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      containers:
        - name: zookeeper
          image: "{{ .Values.image.zookeeper.repository }}:{{ .Values.image.zookeeper.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: client
              containerPort: 2181

          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

          resources:
            requests:
              cpu: {{ .Values.resources.zookeeper.requests.cpu | quote }}
              memory: {{ .Values.resources.zookeeper.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.zookeeper.limits.cpu | quote }}
              memory: {{ .Values.resources.zookeeper.limits.memory | quote }}

          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data

  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.zookeeperStorageSize }}

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: streaming

spec:
  clusterIP: None

  selector:
    app: zookeeper

  ports:
    - name: client
      port: 2181
      targetPort: 2181