apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: streaming
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        role: streaming
      serviceAccountName: streaming-sa
      containers:
        - name: zookeeper
          image: 922967232801.dkr.ecr.us-east-1.amazonaws.com/zookeeper:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: streaming
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181