pipeline {
  agent any

  environment {
    AWS_REGION = "us-east-1"
    TF_DIR     = "infra/platform/eks"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init') {
      steps {
        dir(env.TF_DIR) {
          sh 'terraform init -input=false -reconfigure'
        }
      }
    }

    stage('Terraform Validate') {
      steps {
        dir(env.TF_DIR) {
          sh 'terraform validate'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir(env.TF_DIR) {
          sh '''
            terraform plan \
              -out=tfplan \
              -var-file=platform.tfvars
          '''
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        input message: 'Apply Terraform to create/update EKS?', ok: 'Apply'
        dir(env.TF_DIR) {
          sh 'terraform apply -input=false tfplan'
        }
      }
    }
  }

  post {
    success {
      echo 'EKS provisioning completed successfully.'
    }
    failure {
      echo 'Pipeline failed. Check logs.'
    }
  }
}
