apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: airflow-init
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: airflow-init
    spec:
      restartPolicy: Never
      serviceAccountName: airflow-sa

      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}

      containers:
        - name: airflow-init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              echo "Waiting for PostgreSQL..."
              until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT"; do
                echo "Waiting for database..."
                sleep 5
              done

              echo "Running Airflow DB migrations..."
              airflow db migrate || true

              echo "Creating admin user (if not exists)..."
              airflow users create \
                --username "$_AIRFLOW_WWW_USER_USERNAME" \
                --password "$_AIRFLOW_WWW_USER_PASSWORD" \
                --firstname "$_AIRFLOW_WWW_USER_FIRSTNAME" \
                --lastname "$_AIRFLOW_WWW_USER_LASTNAME" \
                --role "$_AIRFLOW_WWW_USER_ROLE" \
                --email "$_AIRFLOW_WWW_USER_EMAIL" || true

              echo "Creating AWS connection (required for S3 logging)..."

              airflow connections add aws_default \
                --conn-type aws || true

              echo "Airflow initialization completed."

          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMapName }}
            - secretRef:
                name: {{ .Values.envFrom.secretName }}