apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: airflow-worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:15
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for Postgres to be reachable..."
              until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT"; do
                echo "Postgres not ready yet..."
                sleep 5
              done
              echo "Postgres is reachable."
          envFrom:
            - secretRef:
                name: {{ .Values.envFrom.secretName }}

      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["airflow"]
          args: ["celery", "worker"]

          ports:
            - name: logs
              containerPort: 8793

          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMapName }}
            - secretRef:
                name: {{ .Values.envFrom.secretName }}
          env:
            - name: AIRFLOW_CONFIG
              value: "/dev/null"

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: airflow-worker
spec:
  type: ClusterIP
  selector:
    app: airflow-worker
  ports:
    - name: logs
      port: 8793
      targetPort: 8793
