apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: airflow-worker

  template:
    metadata:
      labels:
        app: airflow-worker

    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      serviceAccountName: airflow-sa

      initContainers:
        # -----------------------------
        # Wait for DB (same as API)
        # -----------------------------
        - name: wait-for-db
          image: postgres:15
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT"; do
                sleep 5
              done
          envFrom:
            - secretRef:
                name: {{ .Values.envFrom.secretName }}

        # -----------------------------
        # Delete default airflow.cfg
        # (same as API / scheduler / others)
        # -----------------------------
        - name: delete-airflow-config
          image: busybox
          command: ["sh", "-c"]
          args:
            - rm -f /opt/airflow/airflow.cfg

      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["/entrypoint"]
          args: ["airflow", "celery", "worker"]

          envFrom:
            - configMapRef:
                name: {{ .Values.envFrom.configMapName }}
            - secretRef:
                name: {{ .Values.envFrom.secretName }}