kube-prometheus-stack:

  ##################################
  # CRDs (ARGOCD FIX)
  ##################################
  crds:
    enabled: true

  ##################################
  # PROMETHEUS
  ##################################
  prometheus:
    serviceAccount:
      create: true
      name: prometheus
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::369598751710:role/risk-eks-prometheus-irsa-role

    prometheusSpec:
      retention: 90d

      nodeSelector:
        role: monitoring

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi

      ##################################
      # JENKINS EC2 SCRAPE
      ##################################
      additionalScrapeConfigs:
        - job_name: "jenkins-ec2"
          static_configs:
            - targets:
                - "ip-10-0-1-177.ec2.internal:9100"
        - job_name: pushgateway
          static_configs:
            - targets:
                - pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091
  ##################################
  # GRAFANA
  ##################################
  grafana:

    defaultDashboardsEnabled: true

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL

    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    nodeSelector:
      role: monitoring

    ingress:
      enabled: true
      ingressClassName: alb

      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:369598751710:certificate/67ead6d7-4c24-4a1e-b976-e7aa9ba4aff4
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/group.name: risk-engine
        alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600

      hosts:
        - grafana.pushparag.online
      paths:
        - /

    persistence:
      enabled: true
      storageClassName: gp3
      size: 20Gi

  ##################################
  # ALERTMANAGER
  ##################################
  alertmanager:
    alertmanagerSpec:
      nodeSelector:
        role: monitoring
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi