kube-prometheus-stack:

  ##################################
  # CRDs (ARGOCD FIX)
  ##################################
  crds:
    enabled: true

  ##################################
  # PROMETHEUS
  ##################################
  prometheus:
    serviceAccount:
      create: true
      name: prometheus
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::922967232801:role/risk-engine-prometheus-irsa-role

    prometheusSpec:
      retention: 15d

      nodeSelector:
        role: monitoring

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi

  ##################################
  # GRAFANA
  ##################################
  grafana:

    # ✅ ENABLE DEFAULT DASHBOARDS
    defaultDashboardsEnabled: true

    # ✅ THIS WAS MISSING (LOAD DASHBOARDS)
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL

    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password

    nodeSelector:
      role: monitoring

    ##################################
    # ALB INGRESS
    ##################################
    ingress:
      enabled: true
      ingressClassName: alb

      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:922967232801:certificate/e0af3110-f363-4d3e-85a0-2e428d4cd4a6
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/group.name: risk-engine
        alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600

      hosts:
        - grafana.pushparag.online

      paths:
        - /

    ##################################
    # GRAFANA STORAGE
    ##################################
    persistence:
      enabled: true
      storageClassName: gp3
      size: 20Gi

  ##################################
  # ALERTMANAGER
  ##################################
  alertmanager:
    alertmanagerSpec:
      nodeSelector:
        role: monitoring