apiVersion: v2
name: pushgateway
description: Prometheus Pushgateway
type: application
version: 0.1.0

dependencies:
  - name: prometheus-pushgateway
    version: 2.14.0
    repository: https://prometheus-community.github.io/helm-charts