namespace: streaming

serviceAccount:
  name: streaming-sa
  roleArn: arn:aws:iam::363267429137:role/risk-eks-streaming-s3-irsa-role

envFrom:
  secretName: streaming-infra-secret

image:
  pullPolicy: IfNotPresent

  producer:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/producer
    tag: "25"

  spark:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/spark
    tag: "34"

  zookeeper:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/zookeeper
    tag: "5"

  kafka:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/kafka
    tag: "5"

  kubectl:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/kubectl
    tag: "5"

replicas:
  zookeeper: 1
  kafka: 1

  equityProducer: 0
  fxProducer: 0

  sparkEquity: 0
  sparkFx: 0

marketHolidays:
  # NYSE holidays for 2026
  - "1 1"
  - "1 19"
  - "2 16"
  - "4 3"
  - "5 25"
  - "6 19"
  - "7 3"
  - "9 7"
  - "11 26"
  - "12 25"

storageClassName: gp3
kafkaStorageSize: 10Gi

pvc:
  ivyCache:
    enabled: true
    name: spark-ivy-cache-pvc
    storageClassName: gp3
    size: 5Gi
  zookeeperData:
    enabled: true
    name: zookeeper-data
    storageClassName: gp3
    size: 5Gi
    
nodeSelector:
  role: streaming
