namespace: streaming

serviceAccount:
  name: streaming-sa
  roleArn: arn:aws:iam::363267429137:role/risk-eks-streaming-s3-irsa-role

envFrom:
  secretName: streaming-infra-secret

image:
  pullPolicy: IfNotPresent

  producer:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/producer
    tag: "32"

  spark:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/spark
    tag: "48"

  zookeeper:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/zookeeper
    tag: "5"

  kafka:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/kafka
    tag: "5"

  kubectl:
    repository: 363267429137.dkr.ecr.us-east-1.amazonaws.com/kubectl
    tag: "5"

replicas:
  zookeeper: 1
  kafka: 1

  equityProducer: 0
  fxProducer: 0

  sparkEquity: 0
  sparkFx: 0

marketHolidays:
  # NYSE holidays for 2026
  - "1 1"      # Jan 1
  - "19 1"     # Jan 19
  - "16 2"     # Feb 16
  - "3 4"      # Apr 3
  - "25 5"     # May 25
  - "19 6"     # Jun 19
  - "3 7"      # Jul 3
  - "7 9"      # Sep 7
  - "26 11"    # Nov 26
  - "25 12"    # Dec 25

storageClassName: gp3

kafkaStorageSize: 10Gi
zookeeperStorageSize: 5Gi

nodeSelector:
  role: streaming

spark:
  k8sMasterUrl: k8s://https://kubernetes.default.svc

  executors:
    live: 1
    equityBackfillReplay: 4
    fxBackfillReplay: 10

  live:
    executorCores: 1
    executorMemory: 2g
    driverCores: 1
    driverMemory: 2g

  equityBackfillReplay:
    executorCores: 1
    executorMemory: 2g      # Equity-specific
    driverCores: 1
    driverMemory: 2g        # Equity-specific

  fxBackfillReplay:
    executorCores: 1
    executorMemory: 4g      # FX-specific
    driverCores: 1
    driverMemory: 3g        # FX-specific