namespace: streaming

serviceAccount:
  name: streaming-sa
  roleArn: arn:aws:iam::369598751710:role/risk-eks-streaming-s3-irsa-role

envFrom:
  secretName: streaming-infra-secret

image:
  pullPolicy: IfNotPresent

  producer:
    repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/producer
    tag: "3"

  spark:
    repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/spark
    tag: "6"

  zookeeper:
    repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/zookeeper
    tag: "2"

  kafka:
    repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/kafka
    tag: "2"

  kubectl:
    repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/kubectl
    tag: "2"

replicas:
  zookeeper: 1
  kafka: 1

  equityProducer: 0
  fxProducer: 0

  sparkEquity: 0
  sparkFx: 0

storageClassName: gp3
kafkaStorageSize: 10Gi

pvc:
  ivyCache:
    enabled: true
    name: spark-ivy-cache-pvc
    storageClassName: gp3
    size: 5Gi
  zookeeperData:
    enabled: true
    name: zookeeper-data
    storageClassName: gp3
    size: 5Gi
    
nodeSelector:
  role: streaming
