from django.urls import path
from .views import *

urlpatterns = [
    path("latest-date/", equity_latest_date),
    path("status/", equity_status),
    path("equity/overview/", equity_overview),
    path("equity/managers/", equity_managers),
    path("equity/risk-drivers/", equity_daily_risk_drivers),
    path("equity/alerts/", equity_alerts),
    path("equity/managers-list/", latest_asset_managers),
    path("equity/tickers-list/", latest_tickers),
    path("equity/manager/overview/", equity_manager_overview),
    path("equity/manager/holdings/", equity_manager_holdings),
    path("equity/manager/risk/", equity_manager_risk_contributors),
    path("equity/manager/alerts/", equity_manager_alerts),
    path("equity/ticker/market/", equity_ticker_market),
    path("equity/ticker/volatility/", equity_ticker_volatility),
    path("equity/ticker/risk/", equity_ticker_risk),
    path("equity/ticker/liquidity/", equity_ticker_liquidity),
    path("equity/ticker/fundamentals/", equity_ticker_fundamentals),
    path("equity/ticker/aggregate/", equity_ticker_aggregate),
    path("equity/ticker/managers/", equity_ticker_managers),
    path("equity/position/summary/", equity_position_summary),
    path("equity/position/intelligence/", equity_position_intelligence),
    path("equity/position/alerts/", equity_position_alerts),
    path("fx/overview/", fx_overview, name="fx-overview"),
    path("fx/ticker/", fx_ticker_detail, name="fx-ticker-detail"),
    path("fx/currency/", fx_currency_detail, name="fx-currency-detail"),
    path("bonds/overview/", bond_overview, name="bond-overview"),
    path("bonds/ticker/",bond_ticker_detail,name="bond-ticker-detail"),
    path("loans/overview/", loans_overview, name="loans-overview"),
    path("loans/ticker/", loans_ticker_detail, name="loans-ticker"),
    path("loans/loan/", loan_detail, name="loan-detail"),
    path("derivatives/overview/", derivatives_overview),
    path("derivatives/ticker/", derivatives_ticker_detail),
    path("derivatives/ticker-asset/", derivatives_ticker_asset_class),
    path("collateral/overview/", collateral_overview),
    path("collateral/ticker/", collateral_ticker_detail),
    path("collateral/ticker/asset-class/", collateral_ticker_asset_class),
    path("commodities/overview/", commodities_overview),
    path("commodities/ticker/", commodities_ticker),
    path("commodities/manager/", commodities_manager),
    path("commodities/commodity/", commodities_commodity),
    path('risk-dashboard/', global_risk_dashboard, name='risk_dashboard_api'),
    path("risk/compliance/limits/", compliance_overview),
]
