apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextjs
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YeeshuPushparag/risk-engine.git
    targetRevision: main
    path: helm/nextjs
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nextjs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
