replicaCount: 1

image:
  repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/nextjs
  tag: "19"
  pullPolicy: IfNotPresent

service:
  port: 3000

nodeSelector:
  role: web

envFrom:
  configMapName: nextjs-config

ingress:
  enabled: true
  host: app.pushparag.online
  certificateArn: arn:aws:acm:us-east-1:369598751710:certificate/67ead6d7-4c24-4a1e-b976-e7aa9ba4aff4
  groupName: risk-engine
