replicaCount: 1

image:
  repository: 369598751710.dkr.ecr.us-east-1.amazonaws.com/nextjs
  tag: "22"
  pullPolicy: IfNotPresent

service:
  port: 3000

nodeSelector:
  role: web

envFrom:
  configMapName: nextjs-config

ingress:
  enabled: true
  host: app.pushparag.online
  certificateArn: arn:aws:acm:us-east-1:363267429137:certificate/96bea5e5-6646-4921-8328-0577cfb4f91d
  groupName: risk-engine
