# Generated by Django 5.0.6 on 2026-05-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonddata',
            name='issue_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='market_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='outstanding_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='units_issued',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='units_outstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='vol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
